# Generated by Django 5.1.6 on 2025-03-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_funcionario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento/Setor'),
        ),
    ]
