# Generated by Django 5.1.6 on 2025-03-05 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_departamento_usuario_funcao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome_funcionario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='setor',
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('nome_funcionario', models.CharField(max_length=255, verbose_name='Nome do Funcionário')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('setor', models.CharField(max_length=100, verbose_name='Complemento/Setor')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
