# Generated by Django 5.1.6 on 2025-03-06 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_departamento_remove_usuario_funcao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Falta')),
                ('tipo', models.CharField(choices=[('JUS', 'Justificada'), ('NAO', 'Não Justificada'), ('LIC', 'Licença')], default='NAO', max_length=3)),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('atestado', models.FileField(blank=True, null=True, upload_to='atestados/%Y/%m/', verbose_name='Atestado')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='usuarios.funcionario')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Falta',
                'verbose_name_plural': 'Registros de Faltas',
                'ordering': ['-data'],
            },
        ),
    ]
