# Generated by Django 5.1.6 on 2025-03-06 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_registrofalta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrofalta',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Registro de Falta', 'verbose_name_plural': 'Registros de Faltas'},
        ),
        migrations.RemoveField(
            model_name='registrofalta',
            name='data',
        ),
        migrations.AddField(
            model_name='registrofalta',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final'),
        ),
        migrations.AddField(
            model_name='registrofalta',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Inicial'),
        ),
    ]
