# Generated by Django 5.1.6 on 2025-03-07 13:09

from django.db import migrations

def capitalizar_nomes(apps, schema_editor):
    # Obtém os modelos
    Usuario = apps.get_model('usuarios', 'Usuario')
    Funcionario = apps.get_model('usuarios', 'Funcionario')
    
    # Atualiza nomes de usuários
    for usuario in Usuario.objects.all():
        usuario.nome_completo = ' '.join(word.capitalize() for word in usuario.nome_completo.split())
        usuario.save()
    
    # Atualiza nomes de funcionários
    for funcionario in Funcionario.objects.all():
        funcionario.nome_funcionario = ' '.join(word.capitalize() for word in funcionario.nome_funcionario.split())
        funcionario.nome_empresa = ' '.join(word.capitalize() for word in funcionario.nome_empresa.split())
        funcionario.departamento = ' '.join(word.capitalize() for word in funcionario.departamento.split())
        funcionario.setor = ' '.join(word.capitalize() for word in funcionario.setor.split())
        funcionario.funcao = ' '.join(word.capitalize() for word in funcionario.funcao.split())
        funcionario.save()

def reverter_capitalizacao(apps, schema_editor):
    # Como não podemos reverter com certeza a capitalização original,
    # esta função não faz nada
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_registrofalta_options_and_more'),
    ]

    operations = [
        migrations.RunPython(capitalizar_nomes, reverter_capitalizacao),
    ]
