# Generated by Django 5.1.6 on 2025-03-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_capitalizar_nomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código da Categoria'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='horario',
            field=models.CharField(blank=True, help_text='Ex: 08:00 - 17:00', max_length=100, null=True, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário'),
        ),
    ]
