# Generated by Django 5.1.6 on 2025-03-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_funcionario_categoria_funcionario_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='categoria',
            field=models.CharField(blank=True, choices=[('TRA', 'Trabalhador'), ('EST', 'Estagiário'), ('CTD', 'Empregado sob contrato de trabalho por prazo determinado/intermitente - Lei n°. 9.601/98')], max_length=3, null=True, verbose_name='Categoria'),
        ),
    ]
