# Generated by Django 5.1.6 on 2025-03-07 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_funcionario_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='categoria',
            field=models.CharField(choices=[('TRA', 'Trabalhador'), ('EST', 'Estagiário'), ('CTD', 'Empregado sob contrato de trabalho por prazo determinado/intermitente - Lei n°. 9.601/98')], default='TRA', max_length=3, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='codigo',
            field=models.CharField(default='0000', max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='codigo_categoria',
            field=models.CharField(default='000', max_length=20, verbose_name='Código da Categoria'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='horario',
            field=models.CharField(default='08:00 - 17:00', help_text='Ex: 08:00 - 17:00', max_length=100, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salário'),
        ),
    ]
